In [1]:
# Initial imports
import pandas as pd
from pathlib import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
#load data into pandas dataframe
url = 'https://raw.githubusercontent.com/scrannad/Medicare-Project/annas_branch/numeric_only.csv'
df = pd.read_csv(url)
df.head(25)

,Beneficiaries_with_A_and_B,Fee_for_service_beneficiaries,Med_Advantage_Count,Med_Advantage_Rate,Average_Age,%Female,%Male,%White,%Black,%Hispanic,...,Dialysis_User_Count,Dialysis_User_%,Dialysis_Visits_Per_1000_Users,FQHC_Std_Costs,FQHC_Std_As_%Total,FQHC_Std_Per_Capita,FQHC_Std_Per_User,FQHC_User_Count,FQHC_User_%,FQHC_Visits_Per_1000_Users
0,6444,6186,258,0.0400,71,0.5144,0.4856,0.8810,0.0063,0.0833,...,40,0.0065,741,330449.22,0.0068,53.42,306.26,1079,0.1744,553
1,7463,6861,602,0.0807,73,0.5270,0.4730,0.9469,0.0020,0.0144,...,19,0.0028,437,37418.97,0.0007,5.45,558.49,67,0.0098,39
2,14583,13311,1272,0.0872,71,0.5330,0.4670,0.9246,0.0072,0.0336,...,74,0.0056,665,1257134.97,0.0100,94.44,554.54,2267,0.1703,773
3,18984,17907,1077,0.0567,72,0.5456,0.4544,0.8645,0.0168,0.0782,...,86,0.0048,554,1058899.69,0.0063,59.13,605.43,1749,0.0977,387
4,6134,5925,209,0.0341,70,0.5232,0.4768,0.9391,0.0025,0.0253,...,38,0.0064,659,69716.25,0.0013,11.77,400.67,174,0.0294,86
5,5256,4734,522,0.0993,72,0.5239,0.4761,0.8925,0.0055,0.0606,...,18,0.0038,481,111911.30,0.0027,23.64,592.12,189,0.0399,170
6,100102,93339,6763,0.0676,74,0.5273,0.4727,0.9182,0.0040,0.0373,...,247,0.0026,327,10000026.42,0.0122,107.14,625.00,16000,0.1714,652
7,11777,10945,832,0.0706,52,0.4838,0.5162,0.8429,0.0170,0.0744,...,209,0.0191,2238,1870255.00,0.0156,170.88,704.69,2654,0.2425,1164
8,111879,104284,7595,0.0679,72,0.5227,0.4773,0.9103,0.0053,0.0412,...,456,0.0044,527,11870281.41,0.0127,113.83,636.34,18654,0.1789,706
9,6065,2703,3362,0.5543,67,0.4639,0.5361,0.9811,0.0070,0.0041,...,29,0.0107,1118,1023021.51,0.0388,378.48,596.86,1714,0.6341,4074
10,21767,13018,8749,0.4019,71,0.5380,0.4620,0.9694,0.0097,0.0030,...,71,0.0055,723,397691.08,0.0027,30.55,467.32,851,0.0654,220
11,3549,2056,1493,0.4207,71,0.5233,0.4767,0.9747,0.0112,0.0054,...,13,0.0063,754,861028.35,0.0420,418.79,702.31,1226,0.5963,3121
12,19330,10717,8613,0.4456,70,0.5289,0.4711,0.9244,0.0522,0.0062,...,80,0.0075,834,2629192.73,0.0236,245.33,526.68,4992,0.4658,1754
13,12533,6169,6364,0.5078,71,0.5325,0.4675,0.9752,0.0055,0.0029,...,59,0.0096,1071,622392.29,0.0097,100.89,543.10,1146,0.1858,737
14,7733,4262,3471,0.4489,72,0.5178,0.4822,0.9763,0.0028,0.0028,...,30,0.0070,954,251256.47,0.0056,58.95,483.19,520,0.1220,429
15,10078,4869,5209,0.5169,72,0.5371,0.4629,0.9417,0.0253,0.0051,...,27,0.0055,564,9917.93,0.0002,2.04,413.25,24,0.0049,14
16,4638,3032,1606,0.3463,72,0.5310,0.4690,0.9631,0.0053,0.0059,...,14,0.0046,570,718254.67,0.0264,236.89,680.81,1055,0.3480,1615
17,14132,6932,7200,0.5095,72,0.5365,0.4635,0.9375,0.0238,0.0065,...,44,0.0063,762,114978.65,0.0015,16.59,438.85,262,0.0378,121
18,6909,4838,2071,0.2998,72,0.5308,0.4692,0.9554,0.0263,0.0035,...,20,0.0041,398,692218.57,0.0132,143.08,573.50,1207,0.2495,878
19,16186,8377,7809,0.4825,70,0.5275,0.4725,0.9348,0.0464,0.0032,...,68,0.0081,929,1651757.50,0.0206,197.18,484.81,3407,0.4067,1560
20,7742,3280,4462,0.5763,71,0.5345,0.4655,0.9759,0.0049,0.0076,...,17,0.0052,744,8027.65,0.0002,2.45,334.49,24,0.0073,18
21,12759,6528,6231,0.4884,72,0.5415,0.4585,0.9521,0.0268,0.0058,...,57,0.0087,1183,647465.25,0.0086,99.18,554.34,1168,0.1789,776
22,8830,4072,4758,0.5388,67,0.5091,0.4909,0.9683,0.0187,0.0034,...,32,0.0079,818,1106000.31,0.0241,271.61,637.46,1735,0.4261,2288
23,44755,21446,23309,0.5208,71,0.5356,0.4644,0.9225,0.0512,0.0039,...,180,0.0084,933,1809829.18,0.0081,84.39,504.27,3589,0.1674,597
24,10474,6856,3618,0.3454,72,0.5492,0.4508,0.8995,0.0521,0.0166,...,65,0.0095,1200,288231.62,0.0045,42.04,292.32,986,0.1438,471

In [3]:
X=df.copy()
X.drop('Hospital_Readmit_Rate%', axis=1, inplace=True)
X.head()

,Beneficiaries_with_A_and_B,Fee_for_service_beneficiaries,Med_Advantage_Count,Med_Advantage_Rate,Average_Age,%Female,%Male,%White,%Black,%Hispanic,...,Dialysis_User_Count,Dialysis_User_%,Dialysis_Visits_Per_1000_Users,FQHC_Std_Costs,FQHC_Std_As_%Total,FQHC_Std_Per_Capita,FQHC_Std_Per_User,FQHC_User_Count,FQHC_User_%,FQHC_Visits_Per_1000_Users
0,6444,6186,258,0.0400,71,0.5144,0.4856,0.8810,0.0063,0.0833,...,40,0.0065,741,330449.22,0.0068,53.42,306.26,1079,0.1744,553
1,7463,6861,602,0.0807,73,0.5270,0.4730,0.9469,0.0020,0.0144,...,19,0.0028,437,37418.97,0.0007,5.45,558.49,67,0.0098,39
2,14583,13311,1272,0.0872,71,0.5330,0.4670,0.9246,0.0072,0.0336,...,74,0.0056,665,1257134.97,0.0100,94.44,554.54,2267,0.1703,773
3,18984,17907,1077,0.0567,72,0.5456,0.4544,0.8645,0.0168,0.0782,...,86,0.0048,554,1058899.69,0.0063,59.13,605.43,1749,0.0977,387
4,6134,5925,209,0.0341,70,0.5232,0.4768,0.9391,0.0025,0.0253,...,38,0.0064,659,69716.25,0.0013,11.77,400.67,174,0.0294,86

In [14]:
y=df['Hospital_Readmit_Rate%'].values.reshape(-1,1)
y[:5]

array([[0.1177],
       [0.1528],
       [0.1419],
       [0.1355],
       [0.1065]])

In [15]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [16]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [17]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [18]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [19]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [20]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)

ValueError: ignored