In [10]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("10_year_data.csv")
application_df.head()

/Users/janicemathew/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (87,91,92,95,96,100,101,103,104,106,110) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,YEAR,Geographic_level,State,County,Age_level,Beneficiaries_with_A_and_B,Fee_for_service_beneficiaries,Med_Advantage_Count,Med_Advantage_Rate,Average_Age,...,Pneumonia_<65,Pneumonia_65-74,Pneumonia_75+,UTI_<65,UTI_65-74,UTI_75+,Asthma_<40,LE_Amputation_<65,LE_Amputation_65-74,LE_Amputation_75+
0,1/1/2021,County,WY,Weston,All,1648.0,1484.0,164.0,0.0995,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/1/2021,County,WY,Washakie,All,1926.0,1876.0,50.0,0.0260,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/1/2021,County,WY,Uinta,All,3573.0,2971.0,602.0,0.1685,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/1/2021,County,WY,UNKNOWN,All,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/1/2021,County,WY,Teton,All,3657.0,3388.0,269.0,0.0736,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
application_df.dtypes

YEAR                    object
Geographic_level        object
State                   object
County                  object
Age_level               object
                        ...
UTI_75+                float64
Asthma_<40              object
LE_Amputation_<65       object
LE_Amputation_65-74     object
LE_Amputation_75+       object
Length: 112, dtype: object

In [3]:
application_df['Fee_for_service_beneficiaries'].dtypes

dtype('float64')

In [5]:
application_df.columns.values.tolist()

['YEAR',
 'Geographic_level',
 'State',
 'County',
 'Age_level',
 'Beneficiaries_with_A_and_B',
 'Fee_for_service_beneficiaries',
 'Med_Advantage_Count',
 'Med_Advantage_Rate',
 'Average_Age',
 '%Female',
 '%Male',
 '%White',
 '%Black',
 '%Hispanic',
 '%OtherRace',
 '%Dual_Eligible',
 'Avg_Risk_Score',
 'Total_Standardized_Costs',
 'Total_Std_Risk_Adjusted_Costs',
 'Standardized_Per_Capita_Costs',
 'Standardized_Risk_Adjusted_Per_Capita_Costs',
 'IP_Standardized_Costs',
 'IP_Std_%Total',
 'IP_Std_Per_Capita',
 'IP_Std_Per_User',
 'IP_Users',
 '%Beneficiaries_Using_IP',
 'IP_Covered_Stays_Per_1000',
 'IP_Covered_Days_Per_1000',
 'Hospital_Readmit_Count',
 'Hospital_Readmit_Rate%',
 'ER_Visits_Count',
 'ER_Visits_Per_1000',
 '%ER_Visits',
 'OP_Std_Costs',
 'OP_Std_%Total',
 'OP_Std_Per_Capita_Costs',
 'OP_Std_Per_User_Costs',
 'OP_Users_Count',
 '%_Using_OP',
 'OP_Visits_Per_1000',
 'SNF_Std_Costs',
 'SNF_Std_As_%Total',
 'SNF_Std_Per_Capita',
 'SNF_Std_Per_User',
 'SNF_Users_Count',
 'SNF_Users_%Beneficiaries',
 'SNF_Per_1000_Users',
 'SNF_Days_Per_1000_Users',
 'HH_Std_Costs',
 'HH_Std_As_%Total',
 'HH_Std_Per_Capita',
 'HH_Std_Per_User',
 'HH_User_Count',
 'HH_User_Percent',
 'HH_Per_1000_Users',
 'HH_Visits_Per_1000_Users',
 'Hospice_Std_Costs',
 'Hospice_Std_As_%Total',
 'Hospice_Std_Per_Capita',
 'Hospice_Std_Per_User',
 'Hospice_Count',
 'Hospice_%',
 'Hospice_Per_1000_Users',
 'Hospice_Days_Per_1000_Users',
 'EM_Std_Costs',
 'EM_Std_As_%Total',
 'EM_Std_Per_Capita',
 'EM_Std_Per_User',
 'EM_User_Count',
 'EM_User_%',
 'EM_Events_Per_1000_Users',
 'Dialysis_Std_Costs',
 'Dialysis_Std_As_%Total',
 'Dialysis_Std_Per_Capita',
 'Dialysis_Std_Per_User',
 'Dialysis_User_Count',
 'Dialysis_User_%',
 'Dialysis_Visits_Per_1000_Users',
 'FQHC_Std_Costs',
 'FQHC_Std_As_%Total',
 'FQHC_Std_Per_Capita',
 'FQHC_Std_Per_User',
 'FQHC_User_Count',
 'FQHC_User_%',
 'FQHC_Visits_Per_1000_Users',
 'Diabetes_<65',
 'Diabetes_65-74',
 'Diabetes_75+',
 'COPD_Asthma_40-64',
 'COPD_Asthma_65-74',
 'COPD_Asthma_75+',
 'HTN_<65',
 'HTN_65-74',
 'NTH_75+',
 'CHF_<65',
 'CHF_65-74',
 'CHF_75+',
 'Dehydration_<65',
 'Dehydration_65-74',
 'Dehydration75+',
 'Pneumonia_<65',
 'Pneumonia_65-74',
 'Pneumonia_75+',
 'UTI_<65',
 'UTI_65-74',
 'UTI_75+',
 'Asthma_<40',
 'LE_Amputation_<65',
 'LE_Amputation_65-74',
 'LE_Amputation_75+']

In [4]:
application_df.nunique()

YEAR                      9
Geographic_level          3
State                    54
County                 1856
Age_level                 3
                       ...
UTI_75+                 402
Asthma_<40              209
LE_Amputation_<65       236
LE_Amputation_65-74     147
LE_Amputation_75+        82
Length: 112, dtype: int64

In [12]:
X = application_df[['Age_level', 'Beneficiaries_with_A_and_B', 'Fee_for_service_beneficiaries', 'IP_Standardized_Costs']]
y = application_df['Med_Advantage_Rate']
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:

# Choose a regression algorithm
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

ValueError: could not convert string to float: 'All'

In [14]:
age_levels = application_df['Age_level']
print(age_levels)

0        All
1        All
2        All
3        All
4        All
        ...
30201    <65
30202    All
30203    >65
30204    <65
30205    All
Name: Age_level, Length: 30206, dtype: object